trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - 'main'
  drafts: false

pool:
  vmImage: ubuntu-22.04

steps:
- task: SonarCloudPrepare@2
  displayName: 'Connect to SonarCloud project'
  inputs:
    SonarCloud: 'tm-3558-not-nhsd-sonarcloud'
    organization: 'ullet-experiments'
    scannerMode: 'MSBuild'
    projectKey: 'pr-analysis-spike'
    projectName: 'PR analysis spike'
    extraProperties: |
      sonar.cs.vscoveragexml.reportsPaths=$(Build.ArtifactStagingDirectory)/coverage.xml

# sonar.coverage.jacoco.xmlReportPaths="$(Build.ArtifactStagingDirectory)/coverage.xml"

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'Dummy/Dummy.sln'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: 'Dummy/Dummy.sln'
    arguments: '--configuration Release --no-build --collect "Code Coverage"'

- bash: |
    # Install dotnet-coverage as a global tool
    dotnet tool install --global dotnet-coverage
    dotnet-coverage merge "$(Build.SourcesDirectory)/**/*.coverage" -f xml -o "$(Build.ArtifactStagingDirectory)/coverage.xml"
  displayName: 'Convert coverage report'

- task: SonarCloudAnalyze@2
  displayName: 'Run SonarCloud analysis'
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  displayName: 'Publish SonarCloud analysis result to pipeline'
  inputs:
    pollingTimeoutSec: '300'
